### ISSUE TITLE
filter transactions based on AEX-9 and DEX related entrypoints

### ISSUE THREAD

**Issue by marc0olo** [aeternity/mdw-frontend#155]
## AEX-9
- [ ] transfer
- [x] change allowance
- [ ] mint
- [ ] burn

## DEX
- [x] add liquidity
- [x] remove liquidity
- [x] swap

**Comment by sborrazas** [comment]
I would try to avoid adding filters specific to a single type of transaction to the `/txs` endpoint, since it would be confusing to users. Instead, I think we should add a new endpoint `/contracts/calls` and rename the one we already have to `/contracts/internal-calls`.

You would then be able to do `/contracts/calls?function=add_liquidity` to get all contract calls that have that as a function name

**Comment by marc0olo** [comment]
so from my understanding it's doable by fetching contract calls and filtering out the functions that should be displayed. that's what @ifaouibadi is now aiming for.

I as an enduser want to be able to see all of my DEX related activities as easily accessible as possible. how can we achieve that? currently this seems to be the only way to go.

I need this at least on account level. the account page is the most important place for me as a user. here I am tracking my activities

**Comment by marc0olo** [comment]
closed with #165
